<a href="https://colab.research.google.com/github/HalyshAnton/Python-AI/blob/AI_2_practice/%D0%93%D0%BE%D1%82%D0%BE%D0%B2%D0%B0_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
int64


In [11]:
x = np.array(range(1, 12+1))
x = np.arange(1, 12+1)  # теж саме

x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
x.shape

(12,)

In [10]:
x.dtype

dtype('int64')

# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть результат

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [18]:
new_x = x.reshape((3, 4))
new_x = x.reshape((-1, 4))  # сам порахує кількість рядків

float_x = new_x.astype(np.float32)

print(new_x.dtype)
print(float_x.dtype)

int64
float32


#Завдання 3
Створіть наступні матриці 8х8

In [ ]:
# за замовчуванням всюди нулі


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
x = np.zeros((8, 8), dtype=np.int8)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
# одиниця в рядку 2 стовпчик 3

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
x = np.zeros((8, 8), dtype=np.int8)

x[1, 2] = 1
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
# рядок 3 з одиниць

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
x = np.zeros((8, 8), dtype=np.int8)

x[2] = 1

x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [ ]:
# стовпчик 2 з одиниць

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]])

In [ ]:
# рядки з 2 по 4 з одиниць

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# стовпчики 3 і 4 з одиниць

array([[0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0]])

In [ ]:
# ділянка між рядками 1,4 та стовпчиками 2,4

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# кожен непарний рядок

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# кожен парний стовпчик

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# рядки 4,5 та стовпчики 4,5

array([[0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0]])

In [ ]:
# шахматний порядок

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# діагональ

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

# Завдання 4

Створіть випадкову матрицю 4х3. Замініть усі значення менші за середнє арифметичне на -1

In [26]:
x = np.random.randint(0, 10, size=(4, 3))

x

array([[1, 9, 7],
       [2, 8, 8],
       [2, 3, 0],
       [2, 8, 5]])

In [27]:
mean = np.mean(x)
mean = x.mean()

mean

4.583333333333333

In [28]:
x < mean

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [30]:
x[x < mean] = -1

x

array([[-1,  9,  7],
       [-1,  8,  8],
       [-1, -1, -1],
       [-1,  8,  5]])

# Завдання 5
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [31]:
x = np.random.randint(0, 10, size=(4, 3))

x

array([[0, 9, 1],
       [4, 8, 4],
       [8, 9, 2],
       [5, 9, 1]])

In [33]:
x.sum()
np.sum(x)

60

In [34]:
# сума кожного рядка
# (4, 3) -> (4)
# axis = 1

x.sum(axis=1)

array([10, 16, 19, 15])

In [35]:
# сума кожного стовпчика
# (4, 3) -> (3)
# axis = 0

x.sum(axis=0)

array([17, 35,  8])

# Завдання 6
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [37]:
x

array([[0, 9, 1],
       [4, 8, 4],
       [8, 9, 2],
       [5, 9, 1]])

In [39]:
# (4, 3) -> (4)
# axis = 1

max_row = x.max(axis=1, keepdims=True)

x - max_row

array([[-9,  0, -8],
       [-4,  0, -4],
       [-1,  0, -7],
       [-4,  0, -8]])

In [40]:
max_row - x

array([[9, 0, 8],
       [4, 0, 4],
       [1, 0, 7],
       [4, 0, 8]])

# Завдання 7

Створіть випадкову матрицю 4х3. В кожному стовпчику знайдіть мінімальний елемент.
Також знайдіть індекс мінімального елемента в кожному стовпчику

[[5 7 9]
 [8 2 0]
 [6 8 1]
 [8 0 9]]

мінімуми [5 0 0]
індекси [0 3 1]


In [41]:
x = np.random.randint(0, 10, size=(4, 3))

x

array([[1, 3, 2],
       [7, 2, 2],
       [7, 8, 6],
       [1, 6, 2]])

In [42]:
# (4, 3) -> (3)
# axis = 0

x.min(axis=0)

array([1, 2, 2])

In [43]:
x.argmin(axis=0)

array([0, 1, 0])

# Завдання 8
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 9
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.